version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: 'py37,report,codecov'
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: 'py37,report,codecov'
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: 'py38,report,codecov'
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: 'py38,report,codecov'
      TOXPYTHON: C:\Python38-x64\python.exe
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
    - TOXENV: 'py39,report,codecov'
      TOXPYTHON: C:\Python39\python.exe
      PYTHON_HOME: C:\Python39
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '32'
    - TOXENV: 'py39,report,codecov'
      TOXPYTHON: C:\Python39-x64\python.exe
      PYTHON_HOME: C:\Python39-x64
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '64'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - python -m pip install cython
  - python -m cython --version
  - python scripts/cython_build_src.py
  - python scripts/cython_build_tests.py
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
